---
global:
  pattern: mcad-pattern

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  cicd:
    namespace: devsecops-ci

  app:
    gatling:
      image: quay.io/hybridcloudpatterns/gatling:latest
      repo: https://github.com/hybrid-cloud-demos/spring-petclinic-gatling
    zapImage: quay.io/hybridcloudpatterns/zap2docker-stable
    crdaImage: quay.io/hybridcloudpatterns/crda-image:0.1
    petclinic:
      repo: https://github.com/hybrid-cloud-demos/spring-petclinic
      configRepo: https://github.com/hybrid-cloud-demos/spring-petclinic-config
      image: quay.io/hybridcloudpatterns/spring-petclinic:latest

  git:
    taskImage: image-registry.openshift-image-registry.svc:5000/openshift/tools


main:
  clusterGroupName: hub

  
