apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ubi
  namespace: datamesh
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/ubi:8.7-1037
    referencePolicy:
      type: Source